import type { Database } from "./local";

function iso(offsetDays: number): string {
  return new Date(Date.now() + offsetDays * 86_400_000).toISOString();
}

function day(offsetDays: number): string {
  return iso(offsetDays).slice(0, 10);
}

/** Demo data for the laboratory plan, loaded the first time the app runs. */
export function seedDatabase(): Database {
  return {
    settings: [
      {
        id: "settings",
        plan: "laboratorio",
        store_name: "Laboratorio Inventrio",
        store_email: "contacto@inventrio.test",
        store_phone: "+34 600 000 000",
        store_address: "Av. Central 123",
        currency: "USD",
        tax_rate: 21,
        expiration_alert_days: 30,
        created_at: iso(0),
      },
    ],
    suppliers: [
      {
        id: "sup-1",
        name: "Química Andina",
        contact_name: "Laura Pérez",
        email: "ventas@quimicaandina.test",
        phone: "+34 611 111 111",
        tax_id: "B12345678",
        address: "Polígono Sur, Nave 4",
        notes: "Reactivos y solventes.",
        created_at: iso(-120),
      },
      {
        id: "sup-2",
        name: "MedLab Supplies",
        contact_name: "Carlos Ruiz",
        email: "info@medlab.test",
        phone: "+34 622 222 222",
        tax_id: "B87654321",
        address: "Calle Industria 88",
        notes: "Consumibles y material estéril.",
        created_at: iso(-90),
      },
    ],
    items: [
      {
        id: "item-1",
        sku: "RX-001",
        name: "Etanol absoluto 99.8%",
        category: "reactivos",
        unit: "litro",
        quantity: 24,
        min_stock: 10,
        unit_cost: 18.5,
        location: "Estante A1",
        supplier_id: "sup-1",
        notes: "Inflamable. Almacenar en armario de seguridad.",
        created_at: iso(-80),
      },
      {
        id: "item-2",
        sku: "RX-002",
        name: "Ácido clorhídrico 37%",
        category: "reactivos",
        unit: "litro",
        quantity: 6,
        min_stock: 8,
        unit_cost: 22.9,
        location: "Estante A2",
        supplier_id: "sup-1",
        notes: "Corrosivo.",
        created_at: iso(-78),
      },
      {
        id: "item-3",
        sku: "CS-010",
        name: "Guantes de nitrilo talla M",
        category: "consumibles",
        unit: "caja",
        quantity: 45,
        min_stock: 20,
        unit_cost: 9.4,
        location: "Almacén B",
        supplier_id: "sup-2",
        notes: "",
        created_at: iso(-60),
      },
      {
        id: "item-4",
        sku: "CS-011",
        name: "Tubos de ensayo 15 ml",
        category: "vidrieria",
        unit: "unidad",
        quantity: 320,
        min_stock: 100,
        unit_cost: 0.75,
        location: "Almacén B",
        supplier_id: "sup-2",
        notes: "",
        created_at: iso(-59),
      },
      {
        id: "item-5",
        sku: "MD-100",
        name: "Kit de reactivo glucosa",
        category: "medicamentos",
        unit: "caja",
        quantity: 12,
        min_stock: 5,
        unit_cost: 64,
        location: "Refrigerador 1",
        supplier_id: "sup-2",
        notes: "Conservar entre 2 y 8 °C.",
        created_at: iso(-40),
      },
    ],
    lots: [
      {
        id: "lot-1",
        code: "L-2401",
        item_id: "item-1",
        supplier_id: "sup-1",
        quantity: 12,
        manufactured_at: day(-200),
        expires_at: day(120),
        status: "activo",
        notes: "",
        created_at: iso(-80),
      },
      {
        id: "lot-2",
        code: "L-2402",
        item_id: "item-2",
        supplier_id: "sup-1",
        quantity: 6,
        manufactured_at: day(-160),
        expires_at: day(18),
        status: "activo",
        notes: "Revisar antes de usar.",
        created_at: iso(-78),
      },
      {
        id: "lot-3",
        code: "L-2403",
        item_id: "item-5",
        supplier_id: "sup-2",
        quantity: 12,
        manufactured_at: day(-90),
        expires_at: day(-5),
        status: "activo",
        notes: "Lote vencido, retirar de circulación.",
        created_at: iso(-40),
      },
      {
        id: "lot-4",
        code: "L-2404",
        item_id: "item-3",
        supplier_id: "sup-2",
        quantity: 45,
        manufactured_at: day(-30),
        expires_at: day(400),
        status: "activo",
        notes: "",
        created_at: iso(-30),
      },
    ],
    stock_movements: [
      {
        id: "mov-1",
        item_id: "item-1",
        lot_id: "lot-1",
        type: "in",
        quantity: 12,
        reason: "Compra inicial",
        moved_at: day(-80),
        created_at: iso(-80),
      },
      {
        id: "mov-2",
        item_id: "item-2",
        lot_id: "lot-2",
        type: "in",
        quantity: 10,
        reason: "Compra inicial",
        moved_at: day(-78),
        created_at: iso(-78),
      },
      {
        id: "mov-3",
        item_id: "item-2",
        lot_id: "lot-2",
        type: "out",
        quantity: 4,
        reason: "Consumo ensayo QC-12",
        moved_at: day(-12),
        created_at: iso(-12),
      },
      {
        id: "mov-4",
        item_id: "item-3",
        lot_id: "lot-4",
        type: "in",
        quantity: 45,
        reason: "Reposición mensual",
        moved_at: day(-30),
        created_at: iso(-30),
      },
    ],
    customers: [],
    sales: [],
  };
}
