import type { ModuleConfig } from "@/modules/_core/types";

export const standardsConfig: ModuleConfig = {
  id: "standards",
  slug: "standards",
  title: "Estándares",
  description: "Normas y certificados de calidad para control auditable.",
  icon: "badge-check",
  plans: ["laboratorio"],
  order: 25,
  table: "standards",
  fields: [
    { name: "code", label: "Código del estándar", type: "text", required: true, placeholder: "Ej: STD-001, USP-RS-12345" },
    { name: "name", label: "Nombre", type: "text", required: true },
    { name: "brand", label: "Marca / Fabricante", type: "text", placeholder: "Ej: Sigma-Aldrich, Merck, USP, LGC" },
    { name: "standard_type", label: "Tipo de norma", type: "select", required: true, options: [
      { value: "ISO", label: "ISO" },
      { value: "ASTM", label: "ASTM" },
      { value: "USP", label: "USP" },
      { value: "BP", label: "British Pharmacopoeia (BP)" },
      { value: "EP", label: "European Pharmacopoeia (EP)" },
      { value: "AOAC", label: "AOAC" },
      { value: "NIST", label: "NIST" },
      { value: "Internal", label: "Interna" },
      { value: "Other", label: "Otra" },
    ]},
    { name: "standard_class", label: "Clasificación del estándar", type: "select", required: true, options: [
      { value: "primary", label: "Primario (CRM)" },
      { value: "secondary", label: "Secundario (RM)" },
      { value: "working", label: "Estándar de trabajo" },
      { value: "reference", label: "Material de referencia" },
      { value: "certified", label: "Material certificado (CRM)" },
    ]},
    { name: "version", label: "Versión / Lote del fabricante", type: "text", placeholder: "Ej: 2023, Lot SLBH1234V" },
    { name: "issuing_body", label: "Organismo emisor", type: "text", placeholder: "Ej: ISO, USP, NIST" },
    { name: "certification_body", label: "Organismo certificador", type: "text", placeholder: "Ej: TÜV, SGS, Bureau Veritas" },
    { name: "issue_date", label: "Fecha de emisión / recepción", type: "date" },
    { name: "expiry_date", label: "Fecha de vencimiento", type: "date" },
    { name: "status", label: "Estado", type: "select", required: true, options: [
      { value: "active", label: "Vigente" },
      { value: "pending", label: "Pendiente" },
      { value: "expired", label: "Vencido" },
      { value: "revoked", label: "Revocado" },
    ]},
    { name: "storage_condition", label: "Condición de conservación", type: "select", required: true, options: [
      { value: "ambient", label: "Ambiente (15–30 °C)" },
      { value: "cold", label: "Refrigerado (2–8 °C)" },
      { value: "freezer", label: "Congelado (−20 °C)" },
      { value: "ultra_freezer", label: "Ultracongelado (−80 °C)" },
      { value: "nitrogen", label: "Nitrógeno líquido" },
      { value: "dark", label: "Proteger de la luz" },
      { value: "dry", label: "Lugar seco" },
    ]},
    { name: "weight_received", label: "Peso recibido", type: "number", step: "0.0001", placeholder: "Ej: 100, 0.0500" },
    { name: "weight_unit", label: "Unidad de peso", type: "select", options: [
      { value: "mg", label: "mg" },
      { value: "g", label: "g" },
      { value: "kg", label: "kg" },
      { value: "µg", label: "µg" },
      { value: "mL", label: "mL" },
      { value: "L", label: "L" },
    ]},
    { name: "scope", label: "Alcance", type: "textarea", placeholder: "Describe el alcance de la certificación..." },
    { name: "linked_item_id", label: "Artículo asociado", type: "reference", referenceTable: "items", referenceLabel: "name" },
    { name: "review_frequency_days", label: "Frecuencia de revisión (días)", type: "number", step: "1" },
    { name: "last_reviewed_at", label: "Última revisión", type: "date" },
    { name: "next_review_at", label: "Próxima revisión", type: "date" },
    { name: "notes", label: "Notas", type: "textarea" },
  ],
  columns: [
    { key: "code", label: "Código" },
    { key: "name", label: "Nombre" },
    { key: "brand", label: "Marca" },
    { key: "standard_type", label: "Tipo", format: "badge" },
    { key: "standard_class", label: "Clase", format: "badge" },
    { key: "storage_condition", label: "Conservación", format: "badge" },
    { key: "weight_received", label: "Peso", format: "number" },
    { key: "certification_body", label: "Certificador" },
    { key: "expiry_date", label: "Vencimiento", format: "date" },
    { key: "status", label: "Estado", format: "badge" },
  ],
  searchFields: ["code", "name", "brand", "standard_type", "standard_class", "issuing_body", "certification_body", "version"],
};

export default standardsConfig;
